manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: lequoctrong
      url-base: https://github.com/hachachac159
    - name: zmkfirmware-infused-kim
      url-base: https://github.com/infused-kim
    - name: zmkfirmware-split-battery-report
      url-base: https://github.com/Katona/
    - name: luna
      url-base: https://github.com/pitchayath/
  projects:
    - name: zmk
    
      remote: zmkfirmware
      revision: main

      import: app/west.yml
  self:
    path: config
